# Generated by Django 4.2.4 on 2023-11-23 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateField(blank=True, null=True)),
                ('c_complaint', models.CharField(blank=True, max_length=200, null=True)),
                ('u_loginid', models.IntegerField(blank=True, null=True)),
                ('c_reply', models.CharField(blank=True, max_length=200, null=True)),
                ('c_status', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_date', models.DateField(blank=True, null=True)),
                ('f_feedback', models.CharField(blank=True, max_length=200, null=True)),
                ('u_loginid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabourDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lb_name', models.CharField(blank=True, max_length=50, null=True)),
                ('lb_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('lb_phone', models.IntegerField(blank=True, null=True)),
                ('lb_id_proof', models.FileField(blank=True, null=True, upload_to='id proof ')),
                ('lb_place', models.CharField(blank=True, max_length=50, null=True)),
                ('lb_post', models.CharField(blank=True, max_length=50, null=True)),
                ('lb_district', models.CharField(blank=True, max_length=50, null=True)),
                ('lb_pincode', models.IntegerField(blank=True, null=True)),
                ('lb_photo1', models.ImageField(blank=True, null=True, upload_to='media/labour photo')),
                ('lb_photo2', models.ImageField(blank=True, null=True, upload_to='media/labour photo')),
                ('lb_category', models.CharField(blank=True, max_length=50, null=True)),
                ('lb_gender', models.CharField(blank=True, max_length=5, null=True)),
                ('lb_dob', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_date', models.DateField(blank=True, null=True)),
                ('n_content', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StationsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StationName', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Post', models.CharField(blank=True, max_length=50, null=True)),
                ('District', models.CharField(blank=True, max_length=20, null=True)),
                ('Place', models.CharField(blank=True, max_length=20, null=True)),
                ('Pin', models.IntegerField(blank=True, null=True)),
                ('Latitude', models.IntegerField(blank=True, null=True)),
                ('Longitude', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=8, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('post', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(blank=True, max_length=20, null=True)),
                ('pin', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user profile')),
            ],
        ),
        migrations.CreateModel(
            name='ReportDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('labor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='safekerala_admin.labourdb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safekerala_admin.userdb')),
            ],
        ),
        migrations.AddField(
            model_name='labourdb',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safekerala_admin.stationsdb'),
        ),
        migrations.CreateModel(
            name='CriminalDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_gender', models.CharField(blank=True, max_length=5, null=True)),
                ('cr_dob', models.DateField(blank=True, null=True)),
                ('cr_place', models.CharField(blank=True, max_length=30, null=True)),
                ('cr_post', models.CharField(blank=True, max_length=20, null=True)),
                ('cr_district', models.CharField(blank=True, max_length=10, null=True)),
                ('cr_pincode', models.IntegerField(blank=True, null=True)),
                ('cr_phone', models.IntegerField(blank=True, null=True)),
                ('cr_photo1', models.ImageField(blank=True, null=True, upload_to='criminal photo')),
                ('cr_photo2', models.ImageField(blank=True, null=True, upload_to='criminal photo')),
                ('cr_identification_mark1', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_identification_mark2', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_case', models.CharField(blank=True, max_length=200, null=True)),
                ('cr_action', models.CharField(blank=True, max_length=50, null=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safekerala_admin.stationsdb')),
            ],
        ),
        migrations.CreateModel(
            name='ActionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_status', models.CharField(blank=True, max_length=10, null=True)),
                ('labor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='safekerala_admin.labourdb')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safekerala_admin.reportdb')),
                ('u_loginid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='safekerala_admin.userdb')),
            ],
        ),
    ]
