# Generated by Django 4.2.4 on 2023-11-23 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safekerala_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiondb',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_reports', to='safekerala_admin.reportdb'),
        ),
    ]
