# Generated by Django 4.2.4 on 2023-10-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekerala_admin', '0002_stationsdb_delete_stations'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_gender', models.CharField(blank=True, max_length=5, null=True)),
                ('cr_dob', models.DateField(blank=True, null=True)),
                ('cr_place', models.CharField(blank=True, max_length=30, null=True)),
                ('cr_post', models.CharField(blank=True, max_length=20, null=True)),
                ('cr_district', models.CharField(blank=True, max_length=10, null=True)),
                ('cr_pincode', models.IntegerField(blank=True, null=True)),
                ('cr_phone', models.IntegerField(blank=True, null=True)),
                ('cr_photo1', models.ImageField(blank=True, null=True, upload_to='criminal photo')),
                ('cr_photo2', models.ImageField(blank=True, null=True, upload_to='criminal photo')),
                ('s_loginid', models.IntegerField(blank=True, null=True)),
                ('cr_identification_mark1', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_identification_mark2', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_case', models.CharField(blank=True, max_length=200, null=True)),
                ('cr_action', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
