# Generated by Django 4.2.4 on 2023-11-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safekerala_admin', '0002_alter_actiondb_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiondb',
            name='report',
        ),
    ]
