# Generated by Django 4.2.4 on 2023-10-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekerala_admin', '0003_criminaldb'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lb_name', models.CharField(blank=True, max_length=50, null=True)),
                ('lb_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('lb_phone', models.IntegerField(blank=True, null=True)),
                ('lb_id_proof', models.FileField(blank=True, null=True, upload_to='id proof ')),
                ('lb_place', models.CharField(blank=True, max_length=50, null=True)),
                ('lb_post', models.CharField(blank=True, max_length=50, null=True)),
                ('lb_district', models.CharField(blank=True, max_length=50, null=True)),
                ('lb_pincode', models.IntegerField(blank=True, null=True)),
                ('s_loginid', models.IntegerField(blank=True, null=True)),
                ('lb_photo1', models.ImageField(blank=True, null=True, upload_to='labour photo')),
                ('lb_photo2', models.ImageField(blank=True, null=True, upload_to='labour photo')),
                ('lb_catagory', models.CharField(blank=True, max_length=50, null=True)),
                ('lb_gender', models.CharField(blank=True, max_length=5, null=True)),
                ('lb_dob', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
