# Generated by Django 4.2.4 on 2023-11-28 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safekerala_admin', '0004_labourdb_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedLabourDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lb_name', models.CharField(blank=True, max_length=50, null=True)),
                ('lb_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('lb_phone', models.IntegerField(blank=True, null=True)),
                ('lb_id_proof', models.FileField(blank=True, null=True, upload_to='blocked_labour_id_proof')),
                ('lb_place', models.CharField(blank=True, max_length=50, null=True)),
                ('lb_post', models.CharField(blank=True, max_length=50, null=True)),
                ('lb_district', models.CharField(blank=True, max_length=50, null=True)),
                ('lb_pincode', models.IntegerField(blank=True, null=True)),
                ('lb_photo1', models.ImageField(blank=True, null=True, upload_to='blocked_labour_photo')),
                ('lb_photo2', models.ImageField(blank=True, null=True, upload_to='blocked_labour_photo')),
                ('lb_category', models.CharField(blank=True, max_length=50, null=True)),
                ('lb_gender', models.CharField(blank=True, max_length=5, null=True)),
                ('lb_dob', models.DateField(blank=True, null=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safekerala_admin.stationsdb')),
            ],
        ),
    ]
