# Generated by Django 4.2.4 on 2023-10-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekerala_admin', '0005_rename_lb_catagory_labourdb_lb_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateField(blank=True, null=True)),
                ('c_complaint', models.CharField(blank=True, max_length=2000, null=True)),
                ('u_loginid', models.IntegerField(blank=True, null=True)),
                ('c_reply', models.CharField(blank=True, max_length=200, null=True)),
                ('c_status', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
