# Generated by Django 4.2.4 on 2023-12-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekerala_admin', '0006_alter_complaintdb_u_loginid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintdb',
            name='u_loginid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
