# Generated by Django 4.2.4 on 2023-12-05 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safekerala_admin', '0007_alter_complaintdb_u_loginid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintdb',
            name='u_loginid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='safekerala_admin.userdb'),
        ),
    ]
