# Generated by Django 4.2.4 on 2023-10-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekerala_admin', '0007_feedbackdb_alter_complaintdb_c_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_date', models.DateField(blank=True, null=True)),
                ('n_content', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
