# Generated by Django 4.2.4 on 2023-11-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekerala_admin', '0008_notificationdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationsdb',
            name='password',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='stationsdb',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
