# Generated by Django 4.2.4 on 2023-12-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekerala_admin', '0009_alter_feedbackdb_u_loginid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdb',
            name='r_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
