# Generated by Django 4.2.4 on 2023-11-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekerala_admin', '0009_stationsdb_password_stationsdb_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lb_loginid', models.IntegerField(blank=True, null=True)),
                ('u_loginid', models.IntegerField(blank=True, null=True)),
                ('a_status', models.CharField(blank=True, max_length=10, null=True)),
                ('a_report', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='labourdb',
            name='station_lid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationsdb',
            name='s_loginid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
