# Generated by Django 4.2.4 on 2023-11-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safekerala_admin', '0011_remove_criminaldb_s_loginid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actiondb',
            old_name='lb_loginid',
            new_name='lb_id',
        ),
    ]
