# Generated by Django 4.2.4 on 2023-11-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safekerala_admin', '0013_userdb'),
    ]

    operations = [
    ]
