# Generated by Django 4.2.4 on 2023-11-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekerala_admin', '0014_auto_20231119_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiondb',
            name='lb_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='actiondb',
            name='u_loginid',
            field=models.IntegerField(null=True),
        ),
    ]
