# Generated by Django 4.2.4 on 2023-11-19 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safekerala_admin', '0015_alter_actiondb_lb_id_alter_actiondb_u_loginid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiondb',
            name='lb_id',
        ),
        migrations.AddField(
            model_name='actiondb',
            name='lb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='safekerala_admin.labourdb'),
        ),
        migrations.AlterField(
            model_name='actiondb',
            name='u_loginid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='safekerala_admin.userdb'),
        ),
    ]
