# Generated by Django 4.2.4 on 2023-11-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safekerala_admin', '0016_remove_actiondb_lb_id_actiondb_lb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourdb',
            name='lb_photo1',
            field=models.ImageField(blank=True, null=True, upload_to='media/labour photo'),
        ),
        migrations.AlterField(
            model_name='labourdb',
            name='lb_photo2',
            field=models.ImageField(blank=True, null=True, upload_to='media/labour photo'),
        ),
    ]
