# Generated by Django 4.2.4 on 2023-11-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safekerala_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDB',
        ),
    ]
